//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExternalMvcAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Pid { get; set; }
        public string PName { get; set; }
        public Nullable<int> CatId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
